name: tu_cancha
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^2.3.12
  get_it: ^7.2.0
  dio: ^4.0.6
  logger: ^1.1.0
  intl: ^0.17.0
  sqflite: ^2.0.2+1
  path: ^1.8.0
  blurry_modal_progress_hud: ^1.0.3
  flutter_spinkit: ^5.1.0
    
dev_dependencies:
  mockito: ^5.2.0
  test:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/icons/
